"""
UMAT — kapitola 08: Limita funkce.

Zdroj: `~/Downloads/skriptum_2007_05_29_finalni/texty/8_limita_fce.tex` (skriptum 2007-05-29).
Automaticky vyextrahováno skriptem scripts/extract_umat.py 2026-08-03.

Extrahuje jen \\uloha{content}{result} a \\podul{content}{result}.
Bloky \\begin{ul}{...}\\end{ul} s oddělenou odpovědí v `Řešení:` odstavci
nejsou v tomto exportu — jejich formát vyžaduje ruční extrakci.

Makra rozvinutá: \\zlom → \\frac, \\lz/\\pz → \\langle/\\rangle,
\\tg/\\cotg/\\arctg → \\tan/\\cot/\\arctan.
"""

TASKS = [
    {
        "task_id": 'umat_08_01',
        "content_latex": '$\\lim\\limits_{x \\to -2}\\frac{x^2-4}{x+2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": -4.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_02',
        "content_latex": '$\\lim\\limits_{x \\to -1}\\frac{x^2-2x-3}{2x^2-2x-4}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{2}{3}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_03',
        "content_latex": '$\\lim\\limits_{x \\to 2}\\frac{x^2-5x+6}{x^2-3x+2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": -1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_04',
        "content_latex": '$\\lim\\limits_{x \\to 3}\\frac{x^2+2x-15}{x^2-8x+15}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": -4.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_05',
        "content_latex": '$\\lim\\limits_{x \\to 6}\\frac{5x+6-x^2}{7x-6-x^2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{7}{5}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_06',
        "content_latex": '$\\lim\\limits_{x \\to -2}\\frac{x^2-x-6}{x^3+3x^2+2x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{5}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_07',
        "content_latex": '$\\lim\\limits_{x \\to 2} \\frac{x^2-4}{x^2-3x+2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 4.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_08',
        "content_latex": '$\\lim\\limits_{x \\to 2}\\frac{x^4-16}{x^2-4}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 8.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_09',
        "content_latex": '$\\lim\\limits_{x \\to \\sqrt{3}}\\frac{x^4+x^2-12}{x^4-2x^2-3}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{7}{4}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_10',
        "content_latex": '$\\lim\\limits_{x \\to 2}\\frac{x^3-8}{x-2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 12.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_11',
        "content_latex": '$\\lim\\limits_{x \\to 1}\\frac{3x^2+6x-9}{x^3-1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 4.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_12',
        "content_latex": '$\\lim\\limits_{x \\to -2}\\frac{x^3+2x^2+x+2}{x^2+3x+2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": -5.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_13',
        "content_latex": '$\\lim\\limits_{x \\to 1}\\frac{x^3+2x^2-x-2}{x^2-1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 3.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_14',
        "content_latex": '$\\lim\\limits_{x \\to 2}\\frac{2x^3-3x^2-4}{x^3-4x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{3}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_15',
        "content_latex": '$\\lim\\limits_{x \\to 2}\\frac{x^3-2x^2-4x+8}{x^4-8x^2+16}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{1}{4}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_16',
        "content_latex": '$\\lim\\limits_{x \\to -1}\\frac{x^2-2x-3}{x^3+x^2-2x-2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 4.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_17',
        "content_latex": '$\\lim\\limits_{x \\to 2} \\frac{x^2-2x}{8-x^3}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{1}{6}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_18',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{4x^3-x^2}{2x^5-3x^4+5x^3-2x^2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{1}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_19',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{x^4-2x^2}{x^6+3x^4-2x^2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_20',
        "content_latex": '$\\lim\\limits_{x \\to 1}\\left(\\frac{1}{x-1}-\\frac{3}{x^3-1}\\right)$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_21',
        "content_latex": '$\\lim\\limits_{x \\to 1}\\left(\\frac{1}{1-x}-\\frac{2}{1-x^2}\\right)$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{1}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_22',
        "content_latex": '$\\lim\\limits_{x \\to -2}\\left(\\frac{1}{2+x}-\\frac{12}{8+x^3}\\right)$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{1}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_23',
        "content_latex": '$\\lim\\limits_{x \\to 5}\\frac{x^2-10x+25}{x^3-3x^2-9x-5}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 0.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_24',
        "content_latex": '$\\lim\\limits_{x \\to 3}\\frac{x^4-x^3-5x^2-2x-3}{x-3}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 49.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_25',
        "content_latex": '$\\lim\\limits_{x \\to 2}\\frac{x^4-2x^3+2x^2-5x+2}{x-2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 11.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_26',
        "content_latex": '$\\lim\\limits_{x \\to1}\\frac{x^3-3x+2}{x^4-4x+3}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{1}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_27',
        "content_latex": '$\\lim\\limits_{x \\to-1}\\frac{x^3+3x^2-2}{x^3+2x+3}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{3}{5}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_28',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{1-\\sqrt{x+1}}{x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{1}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_29',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{3-\\sqrt{9-x}}{3x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{1}{18}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_30',
        "content_latex": '$\\lim\\limits_{x \\to 4}\\frac{x^2-16}{\\sqrt{x}-2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 32.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_31',
        "content_latex": '$\\lim\\limits_{x \\to 3}\\frac{x-3}{\\sqrt{x+1}-2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 4.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_32',
        "content_latex": '$\\lim\\limits_{x \\to -2}\\frac{2-\\sqrt{6+x}}{x+2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{1}{4}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_33',
        "content_latex": '$\\lim\\limits_{x \\to 3}\\frac{\\sqrt{x+6}-3\\sqrt{x-2}}{x^2-9}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{2}{9}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_34',
        "content_latex": '$\\lim\\limits_{x \\to 1}\\frac{2-\\sqrt{x+3}}{\\sqrt{x}-1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{1}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_35',
        "content_latex": '$\\lim\\limits\\limits_{x \\to -2}\\frac{2-\\sqrt{x+3}}{\\sqrt{x}-1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": 'neex.', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_36',
        "content_latex": '$\\lim\\limits_{x \\to \\frac{\\pi}{6}}\\frac{2\\sin^2 x + \\sin x -1}{2 \\sin^2 x-5\\sin x +2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": -1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_37',
        "content_latex": '$\\lim\\limits_{x \\to \\pi}\\frac{\\cos^2 x -2 \\cos x -3}{\\cos^2 x-4\\cos x-5}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{2}{3}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_38',
        "content_latex": '$\\lim\\limits_{x \\to \\frac{\\pi}{4}}\\frac{\\sin x-\\cos x}{1-\\tanx}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{\\sqrt{2}}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_39',
        "content_latex": '$\\lim\\limits_{x \\to \\frac{\\pi}{4}}\\frac{\\sin x - \\cos x}{\\cos 2x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{\\sqrt{2}}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_40',
        "content_latex": '$\\lim\\limits_{x \\to \\frac{\\pi}{2}}\\frac{\\sin 2x \\cdot \\cos x}{1+\\cos 2x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_41',
        "content_latex": '$\\lim\\limits_{x \\to 0} \\frac{\\sin^2 2x}{1-\\cos 2x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 2.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_42',
        "content_latex": '$\\lim\\limits_{x \\to \\pi} \\frac{\\sin^2 x}{1+\\cos x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 2.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_43',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{1-\\cos x}{\\sin x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 0.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_44',
        "content_latex": '$\\lim\\limits_{x \\to \\frac{\\pi}{4}}\\frac{\\tanx-1}{\\cotx-1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": -1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_45',
        "content_latex": '$\\lim\\limits_{x \\to}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_46',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{\\tan^2x}{1-\\sqrt{\\cos 2x}}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_47',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{\\sin^2 x}{\\sqrt{3}-\\sqrt{2+\\cos x}}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '4\\sqrt{3}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_48',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{\\tanx}{\\sqrt{1-\\sin x}-\\sqrt{1+\\sin x}}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": -1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_49',
        "content_latex": '$\\lim\\limits_{x \\to \\frac{\\pi}{4}}\\frac{\\cos 2x}{\\sqrt{\\sin x}-\\sqrt{\\cos x}}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-2\\sqrt[4]{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_50',
        "content_latex": '$\\lim\\limits_{x \\to \\pi}\\frac{1-\\sqrt{\\cos x +2}}{\\sin^2 2x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{1}{16}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_51',
        "content_latex": '$\\lim\\limits_{x \\to \\frac{\\pi}{6}}\\frac{2\\sin^2 x- \\cos 2x}{\\sqrt{2\\sin x}-1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 4.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_52',
        "content_latex": '$\\lim\\limits_{x \\to 0} \\frac{\\sin2x}{x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 2.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_53',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{\\sin^2 x}{4x^2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{1}{4}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_54',
        "content_latex": '$\\lim\\limits_{x \\to 0} \\frac{\\sin x+\\sin 3x}{x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 4.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_55',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{4x+\\sin 8x}{4x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 3.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_56',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{\\sin^2 x+x}{10x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{1}{10}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_57',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{\\cos^2 x-1+\\sin 2x}{x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 2.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_58',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{1-\\cos2x}{x \\sin x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 2.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_59',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{\\tanx-\\sin 2x}{x}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": -1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_60',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{1-\\cos x}{x^2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{1}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_61',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{\\sin 4x}{\\sqrt{x+1}-1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 8.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_62',
        "content_latex": '$\\lim\\limits_{x \\to 0}\\frac{1-\\sqrt{\\cos2x}}{x^2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_63',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}\\frac{x^2+3x-4}{1-5x^2}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{1}{5}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_64',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}\\frac{2x^2+7x-2}{6x^3-4x+3}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 0.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_65',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}\\frac{2^{x+3}+4}{2^{x-1}+1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 16.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_66',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}\\frac{\\log x + 18}{2\\log x -17}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{1}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_67',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}\\frac{(x-1)(x-2)(x-3)(x-4)(x-5)}{(5x-1)^5}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '5^{-5}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_68',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}\\frac{3x}{5x-1}\\cdot\\frac{2x^2+1}{x^2+2x-1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{6}{5}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_69',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}\\frac{\\sqrt{x^2+1}-x}{x+1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 0.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_70',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}(x-\\sqrt{x^2+5x})$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{5}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_71',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}\\frac{\\sqrt{x+2}+3\\sqrt{x^2-6}}{2x+1}$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '\\frac{3}{2}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_72',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}(2x-\\sqrt{4x^2+3x})$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "mathlive", "expected": '-\\frac{3}{4}', "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
    {
        "task_id": 'umat_08_73',
        "content_latex": '$\\lim\\limits_{x \\to +\\infty}\\sqrt{x}(\\sqrt{x+2}-\\sqrt{x})$',
        "results": [{"key": "vysledek", "label_latex": "= ", "type": "decimal", "expected": 1.0, "tolerance": 0.0}],
        "cognitive_load": 'C',
    },
]
